name: InstallJmeter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    

      - name: setup-jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo curl -O https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          sudo tar -xvf apache-jmeter-5.6.2.tgz
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          
          java -jar ApacheJMeter.jar -v
